### ISSUE TITLE
No output for git name with space

### ISSUE THREAD

**Issue by aelam** [timqian/weekly-report#2]
通过 `npm install -g weekly-report` 安装

切换到含有git仓库的目录, 没有任何输出
切换到git仓库的下面, 没有任何输出

**Comment by timqian** [comment]
What system did you use? This tool has only tested on my mac.
What version of node did use?
How did you run weekly-report?

**Comment by aelam** [comment]
running on mac
node version:`v5.4.1`
`cd /path/to/git_repo/parent` then run `wr` no output
`cd /path/to/git_repo` then run `wr` no output

**Comment by timqian** [comment]
I tried v5.4.1 on  my mac, but it works fine.

I think maybe it is because you don't have commits in the last 7 days :)

If not, can you try to run 

```
DEBUG=* wr
```

and past the out put here?

**Comment by aelam** [comment]
I was thinking if it's the name matter.
now I am sure  it's the reason. My git user.name contains a space 
```
  index generate log for:  /Users/jenkins/Desktop/components/mskeyboard +89ms
  oneReport gitLogCommentToRun:  cd /Users/jenkins/Desktop/components/mskeyboard && git log --after 2016-12-16 --author Ryan Wang +90ms
```

**Comment by aelam** [comment]
getOneReports.js

```
  const gitLogCommentToRun = `cd ${dirname} && git log --after ${dateStr} --author '${name}'`;
```

**Comment by timqian** [comment]
Cool, I have updated the code according to your comment. Plz install again and try

**Comment by aelam** [comment]
How about the ${dirname} . it also could contain space?
  const gitLogCommentToRun = `cd ${dirname} && git log --after ${dateStr} --author '${name}'`;

**Comment by timqian** [comment]
Yeah, thanks
